### ISSUE TITLE
[Architect v1.0.2] - 2 Monitor Setup crash

### ISSUE THREAD

**Issue by architectbugs** [BlackstarDigitalTeam/KetteringReleases#103]
Architect: v1.0.2
OS: Windows 10
Amp Model: ID:Core Stereo 10 V2
Amp Version: 1.0.2
Description: While moving Blackstar Architect from main screen to secondary screen it freezes in the middle and closes.

**Comment by RichBlackstar** [comment]
Saw someone else mention this. Never had this issue, but will keep investigating
