### ISSUE TITLE
[Architect v1.0.2] - Footswitch control

### ISSUE THREAD

**Issue by architectbugs** [BlackstarDigitalTeam/KetteringReleases#105]
Architect: v1.0.2
OS: Mac OSX 10.13.6
Amp Model: ID:Core Stereo 150
Amp Version: 1.4.1
Description: Drop down for FS13 footswitch Button B that appears in the FS-12 Footcontroller settings doen not work

**Comment by RichBlackstar** [comment]
This is confusing, took me a while to figure out what was going on. Not clear in manual, will bring up
