### ISSUE TITLE
[Architect v1.0.2] - bugs

### ISSUE THREAD

**Issue by architectbugs** [BlackstarDigitalTeam/KetteringReleases#107]
Architect: v1.0.2
OS: Windows 10
Amp Model: ID:Core Stereo 40 V2
Amp Version: 1.0.2
Description: 1) in the window "send feedback " don't work the keys ESC, backspace, left, right, up, down, delete.
 2) need fullscreen
3) "send feedback" on top of any window

**Comment by RichBlackstar** [comment]
I think I've fixed this with additionally adding focus when the bug reporter is up
