### ISSUE TITLE
[Architect v1.0.2] - Poor Connectivity

### ISSUE THREAD

**Issue by architectbugs** [BlackstarDigitalTeam/KetteringReleases#120]
Architect: v1.0.2
OS: Windows 10
Amp Model: Not connected
Amp Version: 
Description: Much like the 'insider' software this lacks consitant connectivity. I have been eagerly awaiting a new application, but it seems you have changed the aesthetic and not the reliability. It's unusable, having to switch the amp on and off to even have a hope of the software detecting the amp, when moving the parameters when finally connected, it crashes to desktop. I have now given up on Blackstar and will be purchasing a different amp and I will never go back.

**Comment by RichBlackstar** [comment]
Brutal
