### ISSUE TITLE
[Architect v1.0.2] - Thanks

### ISSUE THREAD

**Issue by architectbugs** [BlackstarDigitalTeam/KetteringReleases#122]
Architect: v1.0.2
OS: Mac OSX 10.15.7
Amp Model: Silverline Deluxe Head
Amp Version: 1.6.1
Description: Hi all

many thanks i realy like it.
I can now remot setup my amp from the seat at the desk ;-)

have a great day
Juerg Frei

**Comment by RichBlackstar** [comment]
Wholesome
