### ISSUE TITLE
[Architect v1.0.0] - Still can't update

### ISSUE THREAD

**Issue by architectbugs** [BlackstarDigitalTeam/KetteringReleases#123]
Architect: v1.0.0
OS: Windows 10
Amp Model: Not connected
Amp Version: 
Description: I'm using Windows 10... I have moved the .exe file to it's own folder on the C: drive... and outside of the [program files] folder as described... Still unable to update... instead I continue to recieve the message, "INSTALLATION FAILED - Couldn't create a temporary folder to unzip the new version!"

Thanks for any help with this... I will continue using the 'Insider' software until then as I have an ID260 TVP

**Comment by RichBlackstar** [comment]
Believe this was solved in 1.0.2
