### ISSUE TITLE
[Architect v1.0.2] - Flexibility Possibility

### ISSUE THREAD

**Issue by architectbugs** [BlackstarDigitalTeam/KetteringReleases#126]
Architect: v1.0.2
OS: Windows 10
Amp Model: Not connected
Amp Version: 
Description: It'd be great if you made the architect into an app for phones or tablets as well. being able to have that flexibility on the go would be amazing!

**Comment by RichBlackstar** [comment]
Nice idea. Currently not possible with HID API, maybe we will move to MIDI communications soon and this will be possible
