### ISSUE TITLE
[Architect v1.0.2] - Update on Update

### ISSUE THREAD

**Issue by architectbugs** [BlackstarDigitalTeam/KetteringReleases#128]
Architect: v1.0.2
OS: Windows 10
Amp Model: ID:260TVP
Amp Version: 1.5.3
Description: Finally figured out what was happening... while the software was unable to create a folder to update itself... I was able to discover that it had created a folder in my documents fold which had the newst version upgrade... although the software itself wasnt finding it... once I found it...(named "Blackstar Architect_New" It opened fine, and I created a shortcut on my desktop... IT WORKS!!!

**Comment by RichBlackstar** [comment]
Interesting, something wrong with the special directories on some machines perhaps?
