### ISSUE TITLE
[Architect v1.0.0] - Firmware wont upgrade on macbook pro

### ISSUE THREAD

**Issue by architectbugs** [BlackstarDigitalTeam/KetteringReleases#135]
Architect: v1.0.0
OS: Mac OSX 11.2
Amp Model: ID:Core Stereo 40 V3
Amp Version: 1.1.3
Description: 
I have just purchased an icore v3 40 and having hooked it up to my macbook it asks me to upgrade firware and sets about the task then crashes after a few seconds trying to attempt it again, Im guessing this is why my macbook doesnt allow me to upload patches downloaded from your user site.
Is there a fix for this please?

**Comment by RichBlackstar** [comment]
Could be literally anything with this mac, would need a log
