### ISSUE TITLE
[Architect v1.0.2] - Better Interface than Blackstart Insider

### ISSUE THREAD

**Issue by architectbugs** [BlackstarDigitalTeam/KetteringReleases#138]
Architect: v1.0.2
OS: Windows 10
Amp Model: Not connected
Amp Version: 
Description: I like this Architect interface a lot better.
Insider I was getting a log of goofy problems like- in some voices it started acting up where I could change bass, mids, but NOT highs. Kind of buggy. Saving was a kludgey effort, got the job done, but... a lot of keystrokes and mouse movements.

AND with Insider, you had to pick the correct voice 1-6 to save to amp. I am glad that is fixed.

So far, I like Architect interface. I am having fun with it.
Thanks Folks!

**Comment by RichBlackstar** [comment]
Take that, Dan
