### ISSUE TITLE
[Architect v1.0.2] - ID:Core High Power presence and resonance

### ISSUE THREAD

**Issue by architectbugs** [BlackstarDigitalTeam/KetteringReleases#139]
Architect: v1.0.2
OS: Windows 10
Amp Model: ID:Core Stereo 100
Amp Version: 1.4.1
Description: Presence and resonance settings in ID:Core High Power cannot be saved to patches and can only be adjusted on the amp itself, not within the software.

**Comment by RichBlackstar** [comment]
More of a product guys decision... Can easily be done in the future
