### ISSUE TITLE
[Architect v1.0.2] - an error has occurred in the script of the page

### ISSUE THREAD

**Issue by architectbugs** [BlackstarDigitalTeam/KetteringReleases#146]
Architect: v1.0.2
OS: Windows 10
Amp Model: ID:260TVP
Amp Version: 1.6.1
Description: Architect 1.0.2 on Windows 10, Id260TVP: when accessing the community for download patches, each page gives "error has occurred in the script of the page" twice. it apperas to be on each page of the community

**Comment by MarcBlackstar** [comment]
Community
