### ISSUE TITLE
[Architect v1.0.2] - Software no funciona

### ISSUE THREAD

**Issue by architectbugs** [BlackstarDigitalTeam/KetteringReleases#148]
Architect: v1.0.2
OS: Windows 10
Amp Model: Not connected
Amp Version: 
Description: Hola
Mi amplificador es el ID Core2
El OS es Windows 10
Con el amplificador conectado cuando abro el programa aparece una ventana que dice: Reading patches... y de repente el programa se cierra.
Si no conecto el amplificador y abro el programa y me pide conectar el dispositivo. Cuando lo hago el programa se cierra.
¿Cómo se soluciona este error?
Gracias

**Comment by RichBlackstar** [comment]
Sounds like there aren't actually any patches to read, would have advised a factory reset.
