### ISSUE TITLE
[Architect v1.0.2] - NO DEVICE CONNECTED

### ISSUE THREAD

**Issue by architectbugs** [BlackstarDigitalTeam/KetteringReleases#154]
Architect: v1.0.2
OS: Windows 10
Amp Model: Not connected
Amp Version: 
Description: CAN'T CONNECT WITH AMP, SOFTWARE KEEPIS TRYING TO DOWNLOAD PATCHES AND CRASHES.
NEW USB CABLES USED BUT STILL NO GOOD.

**Comment by MarcBlackstar** [comment]
Maybe similar to the IDCore BEAM one?
