### ISSUE TITLE
[Architect v1.0.2] - Recording volume is very low

### ISSUE THREAD

**Issue by architectbugs** [BlackstarDigitalTeam/KetteringReleases#159]
Architect: v1.0.2
OS: Windows 10
Amp Model: ID:Core Stereo 20
Amp Version: 1.2.1
Description: Whenever I record (using the USB device) I can only seem to get low volumes. I tried turning knobs on my system, the BA software and the amp itself, but I cannot seem to resolve this issue. I have an ID:CORE V1 amp.

**Comment by RichBlackstar** [comment]
Flat level coming from USB. Have also had people report that it's too loud. Certainly a user-error jobby
