### ISSUE TITLE
[Architect v1.0.2] - Registration and password recovery is a mess

### ISSUE THREAD

**Issue by architectbugs** [BlackstarDigitalTeam/KetteringReleases#163]
Architect: v1.0.2
OS: Windows 10
Amp Model: ID:Core Stereo 20 V2
Amp Version: 1.0.2
Description: Registration form and password recovery just didn't work, we are in 2021!! Wich company still provide buggy registration?!

**Comment by RichBlackstar** [comment]
Agree, community needs complete revamp
