### ISSUE TITLE
[Architect v1.0.2] - Blackstar Architect v1.0.2 no device found

### ISSUE THREAD

**Issue by architectbugs** [BlackstarDigitalTeam/KetteringReleases#165]
Architect: v1.0.2
OS: Windows 10
Amp Model: Not connected
Amp Version: 
Description: aving troubles with the architect software - it is not finding my device.Worked fine with Insider.
I have un-installed all previous insider software, still "no device found" in Architect.The amp still functions as a speaker for my computer so connectivity is not an issue.
Amp: Blackstar ID Core 40 v2PC with Windows 10 pro.
Thank you for any help you can provide

**Comment by RichBlackstar** [comment]
Would have been a useful case for the issue had the user left contact details...
