### ISSUE TITLE
[Architect v0.0.11] - Eric Smith - No device detected

### ISSUE THREAD

**Issue by architectbugs** [BlackstarDigitalTeam/KetteringReleases#17]
Hi, plugged in USB and No Device Detected displayed. Restarted Architect - no joy. Rebooted Amp - no joy. Rebooted MacOS - no joy.  Insider picks up amp via same USB without issue.

Cheers

**Comment by MarcBlackstar** [comment]
macOS HighSierra
IDCore 20 (Version?)

**Comment by JoshBlackstar** [comment]
ID:Core 20 V2 direct into Macbook pro
