### ISSUE TITLE
[Architect v1.0.2] - Updated Tones

### ISSUE THREAD

**Issue by architectbugs** [BlackstarDigitalTeam/KetteringReleases#175]
Architect: v1.0.2
OS: Windows 10
Amp Model: ID:Core Stereo 10 V2
Amp Version: 1.0.2
Description: With the New Architect Studio it would be great if Dave would work us some fresh Voiceings not the same old Presets for older Model Amps like the ID:Core 10 V 2  I'm using right now . Thanks

**Comment by RichBlackstar** [comment]
Who is Dave?
