### ISSUE TITLE
[Architect v1.0.2] - Typo - Footcontroller MOE

### ISSUE THREAD

**Issue by architectbugs** [BlackstarDigitalTeam/KetteringReleases#176]
Architect: v1.0.2
OS: Mac OSX 10.14.6
Amp Model: ID:Core Stereo 40 V3
Amp Version: 1.1.3
Description: Hi, Andy Guitar Geek here.
I noticed that the Architect software  has a typo. It says Footcontroller MOE instead of MODE

I am using V3 of the id core amps.

**Comment by RichBlackstar** [comment]
This has been fixed
