### ISSUE TITLE
[Architect v1.0.2] - ok guys

### ISSUE THREAD

**Issue by architectbugs** [BlackstarDigitalTeam/KetteringReleases#177]
Architect: v1.0.2
OS: Windows 10
Amp Model: Not connected
Amp Version: 
Description: Ok so I was in 90% cases using blackstat insider as just metronome with my combo not connected to PC. 

Now with Architect software I have to have it plugged to even start program.

I mean its just useless for me now.

**Comment by RichBlackstar** [comment]
Google metronome, bro
