### ISSUE TITLE
[Architect v1.0.2] - ok one more mail

### ISSUE THREAD

**Issue by architectbugs** [BlackstarDigitalTeam/KetteringReleases#178]
Architect: v1.0.2
OS: Windows 10
Amp Model: ID:Core Stereo 10 V2
Amp Version: 1.0.2
Description: So I just wrote feedback about having discconected (from PC) guitar combo as I use it mostly as metronome. 

Surprise I found old and dusty mini usb wire (I mean mini USB) and connected to PC. 

No metronome I mean are you fucking kidding me. No seriously are you fucking kidding me.

**Comment by RichBlackstar** [comment]
Managed to connect with a new USB. Google metronome, bro
