### ISSUE TITLE
[Architect v0.0.11] - Ugurcan Taskin - No Device Connected

### ISSUE THREAD

**Issue by architectbugs** [BlackstarDigitalTeam/KetteringReleases#18]
Upon launch, the application indicates "no device connected". However Insider recognizes that the device is connected, alond with other DAWs such as garageband and ableton.

**Comment by MarcBlackstar** [comment]
macOS Mojave
IDCore 10 (version?)

**Comment by JoshBlackstar** [comment]
ID:Core 10 V2 direct into Macbook air
