### ISSUE TITLE
[Architect v1.0.2] - ID core 10 Stereo doesnt hold the patche

### ISSUE THREAD

**Issue by architectbugs** [BlackstarDigitalTeam/KetteringReleases#182]
Architect: v1.0.2
OS: Windows 10
Amp Model: ID:Core Stereo 10
Amp Version: 1.2.1
Description: I can mount patches in various voice sections, but after disconnecting the USB cable,the voice knob does not change the voices. Also, after pressing the manual button, all patches disappear.
can help me out? I bought the ID core years ago and Im from Turkey :)

**Comment by RichBlackstar** [comment]
> after disconnecting the USB cable,the voice knob does not change the voices

The cable has been disconnected... Maybe he is referring to local patches with won't be saved internally.

>after pressing the manual button, all patches disappear.

Is he using patches without saving them? What is the manual button? so many follow up questions...
