### ISSUE TITLE
[Architect v1.0.0] - ID Core v3 not detecting on macos 10.15.7

### ISSUE THREAD

**Issue by architectbugs** [BlackstarDigitalTeam/KetteringReleases#187]
Architect: v1.0.0
OS: Mac OSX 10.15.7
Amp Model: Not connected
Amp Version: 
Description: I see the OS has detected the amp and I can play audio through it. But Architect doesn't detect the device.

**Comment by RichBlackstar** [comment]
This would be a good case to view the logger, but no contact details have been left
