### ISSUE TITLE
[Architect v1.0.2] - No Device Connected

### ISSUE THREAD

**Issue by architectbugs** [BlackstarDigitalTeam/KetteringReleases#188]
Architect: v1.0.2
OS: Windows 10
Amp Model: Not connected
Amp Version: 
Description: I've plugged the USB data lead into the amp and computer case, windows recognieses the amp and I can even play music through it but Architect refuses to recognise it's connected

**Comment by RichBlackstar** [comment]
This would be a good case to identify the logger, but user hasn't supplied contact information
