### ISSUE TITLE
[Architect v1.0.2] - Update Architect

### ISSUE THREAD

**Issue by architectbugs** [BlackstarDigitalTeam/KetteringReleases#189]
Architect: v1.0.2
OS: Windows 10
Amp Model: Silverline Standard
Amp Version: 1.6.1
Description: I have watched on YouTube this video: https://www.youtube.com/watch?v=WeVQ1y_T0Y4, where software Architect includes a noise gate and several cabinets. My amp is Silverline standard and does not have neither noise gate pedal nor other cabinets. Could you update Architect?. My email: manolunam@gmail.com

**Comment by RichBlackstar** [comment]
Silverline doesn't have these features. The video he has linked to is ID:Core V3, not the same
