### ISSUE TITLE
[Architect v1.0.2] - Patch conflict

### ISSUE THREAD

**Issue by architectbugs** [BlackstarDigitalTeam/KetteringReleases#198]
Architect: v1.0.2
OS: Mac OSX 10.11.6
Amp Model: ID:Core Stereo 10 V2
Amp Version: 1.0.2
Description: Can not find patch directory setting in Architect to set patch directory.  I automatically reads my Fender Mustang amp models in the Fender folder of my Documents directory (Mac OSX). I'd like this ID Core 10 & 40 (I own) to have a seprate patch directory & not use the Fender patchers that are for anoter Amp. Any advise? MacDillon@sbcglobal.net

**Comment by RichBlackstar** [comment]
This should be in Architect. Realistically need to allow users to set their own directory for their patches. 

Issue has been raised here: https://github.com/BlackstarDigitalTeam/Kettering/issues/136
