### ISSUE TITLE
[Architect v0.0.11] - Porgram Shuts down 

### ISSUE THREAD

**Issue by architectbugs** [BlackstarDigitalTeam/KetteringReleases#21]
As soon as it pairs with the head the program stops running.

**Comment by JoshBlackstar** [comment]
This is from Anthony Cabanas
OS: Windows 10
Amp: ID:60TVP Head

He said in an email that Architect loads fine without his amp connected, but when he connects his amp or tries to startup architect with the amp connected Architect crashes.
