### ISSUE TITLE
[Architect v1.0.2] - not connected 

### ISSUE THREAD

**Issue by architectbugs** [BlackstarDigitalTeam/KetteringReleases#214]
Architect: v1.0.2
OS: Windows 10
Amp Model: Not connected
Amp Version: 
Description: i have my blackstar amp connected but it still says not connected solve please, its same with insider an thats why i downloaded this but it doesnt work too

**Comment by RichBlackstar** [comment]
User error (or amp fault) somewhere, most likely a USB issue
