### ISSUE TITLE
[Architect v1.0.0] - not able to open or view the full scrreen

### ISSUE THREAD

**Issue by architectbugs** [BlackstarDigitalTeam/KetteringReleases#228]
Architect: v1.0.0
OS: Windows 10
Amp Model: ID:Core Stereo 20 V2
Amp Version: 1.0.2
Description: the window of architech on my laptop is not fully visible. the bottom buttons are not viewable or usable as they are out of sight. i use lenovo yoga 520 laptop

**Comment by RichBlackstar** [comment]
Fixed in the next minor release
