### ISSUE TITLE
[Architect v1.0.2] - Unable to maximize the app

### ISSUE THREAD

**Issue by architectbugs** [BlackstarDigitalTeam/KetteringReleases#232]
Architect: v1.0.2
OS: Windows 10
Amp Model: Not connected
Amp Version: 
Description: I'm unable to maximize the app and make it fit the screen. Some of the controls are at the bottom of the screen and its difficult to access them. Could you please look into this and resolve this soon?

**Comment by RichBlackstar** [comment]
Fixed in the new minor release
