### ISSUE TITLE
[Architect v1.0.2] - Amp will not connect to computer

### ISSUE THREAD

**Issue by architectbugs** [BlackstarDigitalTeam/KetteringReleases#237]
Architect: v1.0.2
OS: Windows 10
Amp Model: Not connected
Amp Version: 
Description: When I try to connect my ID Core V3 to my computer I get a message saying that my USB device is not recognized.  I have tried a new cable, restarted my computer, factory reset the amp, tried other USB ports, uninstalled the software and reinstalled it, and tried to download ASIO.  Non of that works.  Please help cdjpart1@gmail.com

**Comment by RichBlackstar** [comment]
Enquired with Maxx

**Comment by RichBlackstar** [comment]
User wasn't much help as they eventually got it working before we could send a test Architect with a fix
