### ISSUE TITLE
[Architect v1.0.2] - Community access

### ISSUE THREAD

**Issue by architectbugs** [BlackstarDigitalTeam/KetteringReleases#242]
Architect: v1.0.2
OS: Windows 10
Amp Model: Not connected
Amp Version: 
Description: Would be great if we can access the blackstar community when not connected to the amp. I sometimes want to search for patches in advance when I don't have my amp at hand.

**Comment by RichBlackstar** [comment]
Not a bad idea

**Comment by RichBlackstar** [comment]
Placed in Kettering issues to investigate
