### ISSUE TITLE
[Architect v1.0.2] - Bricked Blackstar ID 10

### ISSUE THREAD

**Issue by architectbugs** [BlackstarDigitalTeam/KetteringReleases#245]
Architect: v1.0.2
OS: Windows 10
Amp Model: Not connected
Amp Version: 
Description: The Architect program tryed to update the firmware but bricked the amplifier. What can you do to help me ?? miclun@pm.me

**Comment by RichBlackstar** [comment]
Passed on customer's details for Maxx to handle
