### ISSUE TITLE
[Architect v1.0.1] - ID Core 40 v1

### ISSUE THREAD

**Issue by architectbugs** [BlackstarDigitalTeam/KetteringReleases#33]
Architect: v1.0.1
OS: Mac OSX 10.15.7
Amp Model: Not connected
Amp Version: 
Description: Amp is not being found by Architect. Not sure if it is supported ot not since I didn't see any requirements for Architect. Been waiting since Insider was not updated for OS, and it looks like this doesn't support it either. Nice.

**Comment by MarcBlackstar** [comment]
I did test on Windows and Mac and it connects correctly... 🤔
