### ISSUE TITLE
[Architect v1.0.1] - Does not work with v2 amp

### ISSUE THREAD

**Issue by architectbugs** [BlackstarDigitalTeam/KetteringReleases#36]
Architect: v1.0.1
OS: Mac OSX 10.13.6
Amp Model: Not connected
Amp Version: 
Description: Description...

**Comment by MarcBlackstar** [comment]
![image](https://user-images.githubusercontent.com/64251878/104428678-ac4d8800-557c-11eb-9e8b-0f6ac4e47757.png)
