### ISSUE TITLE
[Architect v1.0.1] - cant connect to ID:260TVP

### ISSUE THREAD

**Issue by architectbugs** [BlackstarDigitalTeam/KetteringReleases#51]
Architect: v1.0.1
OS: Mac OSX 11.1
Amp Model: Not connected
Amp Version: 
Description: am unable to connect to ID:260TVP using Macbook, OS Big Sur. have used Insider on a window based computer and updated the amp to the latest available firmware 1.6.1. still unable to connect to amp in Architect on Mac. Mac can see the amp plugged in to the USB port and recognises it correctly. Please update me Mrkjbradley@hotmail.com

**Comment by RichBlackstar** [comment]
Pretty sure Marc got in touch with this guy. He ended up getting it working on a different machine and never got back in touch
