### ISSUE TITLE
[Architect v1.0.1] - no resizeable window

### ISSUE THREAD

**Issue by architectbugs** [BlackstarDigitalTeam/KetteringReleases#58]
Architect: v1.0.1
OS: Windows 10
Amp Model: Not connected
Amp Version: 
Description: why can I not resize the window for Architect.  I cannot maximise either.

The window does not fit my laptop screen as it goes off the bottom of the screen ... even if I move the windows 10 window bar at the top off screen.  This is bad in 2021

**Comment by RichBlackstar** [comment]
Fixed in next minor release
