### ISSUE TITLE
[Architect v1.0.0] - Won't Update From V1.0.0 to V1.0.1

### ISSUE THREAD

**Issue by architectbugs** [BlackstarDigitalTeam/KetteringReleases#68]
Architect: v1.0.0
OS: Windows 10
Amp Model: Not connected
Amp Version: 
Description: Hi,
I've downloaded the Architect software to replace Insider. I've copied the folder from the zip file to the old location in c:\program files (x86)\Blackstar Amplification Ltd\Blackstar Architect
When I click on update, it downloads the something (8.1MB). However when Architect restarts it's still on version 1.0.0. and wants to download the latest.
Any idea's?
Thanks Pete

**Comment by RichBlackstar** [comment]
Marc added a check for whether the app is in Program Files, where it won't work. This alerts user to move app for it to function
