### ISSUE TITLE
[Architect v1.0.1] - Vםןבקoice changes after using the tuner

### ISSUE THREAD

**Issue by architectbugs** [BlackstarDigitalTeam/KetteringReleases#78]
Architect: v1.0.1
OS: Windows 10
Amp Model: ID:Core Stereo 10 V2
Amp Version: 1.0.2
Description: I change the voice using the architecht only. Enable the tuner, disable the tuner - the voice returns to the setting of the physical button. This doesn't happen with any other parameter.

**Comment by RichBlackstar** [comment]
Fixed this for next release (FW issue, not Architect issue)
