### ISSUE TITLE
[Architect v1.0.1] - Mouse cursor sticks

### ISSUE THREAD

**Issue by architectbugs** [BlackstarDigitalTeam/KetteringReleases#86]
Architect: v1.0.1
OS: Windows 10
Amp Model: ID:Core Stereo 20
Amp Version: 1.2.1
Description: - Click the info icon (i) by VERSION 1.2.1 in the Settings menu.
- Dialog "NO NEW FW AVAILABLE".
- Click OK.
- Mouse cursor turns to hourglass, remains hourglass until you take focus away from Architect.

**Comment by RichBlackstar** [comment]
Can't seem to replicate in v.1.0.2, so must assume it was fixed
